# Generated by Django 3.1.1 on 2021-04-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210409_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='stack',
            field=models.TextField(default='Not yet processed', null=True),
        ),
    ]
